### ISSUE TITLE
Config as file?

### ISSUE THREAD

**Issue by muluffel** [seanhweb/Twitch-Text-to-Speech#19]
Hey,

first of all: I love that tool.
I wanted to know if it was possible to change the code so that the config (channel name, polly checkbox, moderators checkbox, chatter anme checkbox and voice selection) would be saved to a file. 
This way I wouldn't have to set those things every time I reload and I could use the tool for what I intended: Having a TTS on a seperated audio source on my mixer so I can have the chat being read out only to me (not the stream). 
With it opened in the browser, I cannot change the audio output without changing the output for my whole browser. If I could just let it always reuse my config after a reload I could set it up in OBS as a Browser Source and have its monitor audio output bound to my dedicated audio output. 

Do you understand my thoughts?
Let me know if this would be possible to add

**Comment by muluffel** [comment]
--> feature request / enhancement

**Comment by seanhweb** [comment]
This _should_ be possible, but I don't want to make a guarantee. Truthfully, I'm not too familiar with using a browser source inside OBS.

I'll experiment with this and try and get it in the next update. 

Thanks for using the tool, and I'm glad it's helping you!

**Comment by muluffel** [comment]
We modified the code ourselves  to test it. Kinda works but browsers need an interaction before they play audio. Normally OBS does this interaction - I can play all things you can think of via a browser source. But even if I manually interact with the browser source it doesn't play audio. 
I don't get why. Maybe you can figure that out. When opening my modified one in my browser I just need to click somewhere and it works. Kinda confused

**Comment by seanhweb** [comment]
I wrote some code in a different branch to test, and I'm getting similar results. This code checks for ?channelname=channel in the URL, and if a channel is detected auto starts the process. 

https://github.com/seanhweb/Twitch-Text-to-Speech/blob/01b0b965055c9b0b4a585554d7b7a1632f0c2988/public/app.js#L258-L263

If you click "Control Audio via OBS", the TTS does not play inside OBS. _However_, if you click "Use Amazon Polly", it does. 

It looks like OBS does not play nicely with text to speech inside the browser. Using Amazon Polly, it generates an mp3 of the speech rather than the browser reading the message with it's own API. This method appears to work over having the browser generate it. 

Going forward - I'm going to create a way to save settings in the URL, so that you can use a specific URL to access your preferred settings. I will also refine amazon polly speech so it's faster and doesn't cut everyones messages off.

**Comment by seanhweb** [comment]
PR #21 is the start of settings implementation. It is now live. 

Note that Amazon Polly is still having some issues and messages still cut each other off. But this should work for now until that is fixed.
